import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CalendarClock, Copy, Mail, Play, Trophy, Users } from "lucide-react";
import { toast } from "sonner";
import { apiGet, apiPost } from "@/lib/api";
import type { ReportOverview, ReportRun } from "@/lib/cms";

export function ReportPanel() {
  const queryClient = useQueryClient();
  const report = useQuery({ queryKey: ["weekly-report"], queryFn: () => apiGet<ReportOverview>("/admin/reports") });
  const run = useMutation({ mutationFn: () => apiPost<ReportRun>("/admin/reports/run"), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ["weekly-report"] }); toast.success("Simulasi laporan mingguan berhasil dibuat"); }, onError: () => toast.error("Simulasi laporan gagal") });
  const data = report.data;
  const metrics = [
    { label: "Pendaftar", value: data?.preview.total ?? 0, icon: Users },
    { label: "Lewat SLA", value: data?.preview.overdue ?? 0, icon: CalendarClock },
    { label: "Duplikat", value: data?.preview.duplicates ?? 0, icon: Copy },
  ];

  return <section data-testid="report-panel">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div className="mb-3 inline-flex rounded-full bg-amber-100 px-3 py-1.5 text-[10px] font-extrabold uppercase tracking-wider text-amber-800" data-testid="report-simulation-badge">Simulasi — Resend belum diaktifkan</div><h1 className="font-heading text-3xl font-extrabold text-[#0a3358]" data-testid="report-heading">Laporan mingguan pimpinan</h1><p className="mt-2 text-sm text-slate-500">Ringkasan otomatis setiap Senin pukul 07.00 WIB.</p></div><button type="button" onClick={() => run.mutate()} disabled={run.isPending} className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-amber-400 px-5 text-xs font-extrabold text-[#092c4c]" data-testid="report-run-simulation"><Play size={15} /> Jalankan simulasi</button></div>
    <div className="mt-6 grid gap-4 lg:grid-cols-[1.2fr_.8fr]"><article className="rounded-2xl border border-slate-200 bg-white p-5" data-testid="report-preview-card"><div className="flex items-center gap-2 text-[#0f4c81]"><Mail size={17} /><h2 className="text-sm font-extrabold">Preview ringkasan 7 hari</h2></div><div className="mt-5 grid gap-3 sm:grid-cols-3">{metrics.map(({ label, value, icon: Icon }, index) => <div key={label} className="rounded-xl bg-slate-50 p-4" data-testid={`report-metric-${index + 1}`}><Icon size={16} className="text-emerald-600" /><strong className="mt-3 block text-2xl text-[#0a3358]">{value}</strong><span className="text-[10px] font-bold text-slate-500">{label}</span></div>)}</div><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-slate-100 p-4"><span className="text-[10px] font-bold uppercase text-slate-400">Jurusan terpopuler</span><strong className="mt-2 flex items-center gap-2 text-sm text-slate-700"><Trophy size={15} className="text-amber-500" />{data?.preview.top_major ?? "—"}</strong></div><div className="rounded-xl border border-slate-100 p-4"><span className="text-[10px] font-bold uppercase text-slate-400">Petugas tersibuk</span><strong className="mt-2 flex items-center gap-2 text-sm text-slate-700"><Users size={15} className="text-blue-500" />{data?.preview.busiest_officer ?? "—"}</strong></div></div></article><article className="rounded-2xl bg-[#092c4c] p-5 text-white" data-testid="report-schedule-card"><CalendarClock className="text-emerald-300" /><h2 className="mt-4 font-heading text-lg font-extrabold">Jadwal pengiriman</h2><p className="mt-2 text-sm text-slate-300">{data?.schedule ?? "Setiap Senin, 07.00 WIB"}</p><div className="mt-5 space-y-3 text-xs"><p><span className="block text-[9px] uppercase text-slate-400">Penerima dummy</span>{data?.recipient}</p><p><span className="block text-[9px] uppercase text-slate-400">Pengirim</span>{data?.sender}</p><p><span className="block text-[9px] uppercase text-slate-400">Jadwal berikutnya</span>{data?.next_run ? new Date(data.next_run).toLocaleString("id-ID") : "—"}</p></div></article></div>
    <div className="mt-5 overflow-hidden rounded-2xl border border-slate-200 bg-white" data-testid="report-run-history"><div className="border-b border-slate-100 px-5 py-4"><h2 className="text-sm font-extrabold text-slate-800">Riwayat laporan</h2></div>{data?.runs.map((item) => <article key={item.id} className="flex items-center justify-between gap-4 border-b border-slate-100 p-4 last:border-0" data-testid={`report-run-${item.id}`}><div><strong className="text-xs text-slate-700">{item.trigger === "manual" ? "Simulasi manual" : "Jadwal otomatis"}</strong><p className="mt-1 text-[10px] text-slate-400">{new Date(item.created_at).toLocaleString("id-ID")} · {item.recipient}</p></div><span className="rounded-full bg-amber-100 px-2.5 py-1 text-[9px] font-extrabold uppercase text-amber-700">{item.status}</span></article>)}{data?.runs.length === 0 && <div className="p-8 text-center text-sm text-slate-400">Belum ada simulasi.</div>}</div>
  </section>;
}