import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { RotateCcw, Save, Settings2 } from "lucide-react";
import { toast } from "sonner";
import { apiGet, apiPatch, apiPost } from "@/lib/api";
import type { WhatsAppTemplate } from "@/lib/cms";

export function WhatsAppTemplatePanel() {
  const queryClient = useQueryClient();
  const templates = useQuery({ queryKey: ["whatsapp-templates"], queryFn: () => apiGet<WhatsAppTemplate[]>("/admin/whatsapp-templates") });
  const update = useMutation({ mutationFn: ({ key, payload }: { key: string; payload: Record<string, unknown> }) => apiPatch<WhatsAppTemplate>(`/admin/whatsapp-templates/${key}`, payload), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ["whatsapp-templates"] }); toast.success("Template WhatsApp disimpan"); } });
  const reset = useMutation({ mutationFn: (key: string) => apiPost<WhatsAppTemplate>(`/admin/whatsapp-templates/${key}/reset`), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ["whatsapp-templates"] }); toast.success("Template dipulihkan ke default"); } });
  return <section data-testid="whatsapp-template-panel"><div><p className="text-xs font-extrabold uppercase tracking-[.18em] text-emerald-600">Super Admin</p><h1 className="mt-2 font-heading text-3xl font-extrabold text-[#0a3358]" data-testid="template-heading">Template WhatsApp</h1><p className="mt-2 text-sm text-slate-500">Gunakan variabel <code>{"{nama}"}</code>, <code>{"{jurusan}"}</code>, <code>{"{petugas}"}</code>, dan <code>{"{sekolah}"}</code>.</p></div><div className="mt-7 grid gap-4 xl:grid-cols-2">{templates.data?.map((template) => <form key={`${template.key}-${template.updated_at}`} onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); update.mutate({ key: template.key, payload: { content: String(data.get("content")), is_active: data.get("is_active") === "on" } }); }} className="rounded-2xl border border-slate-200 bg-white p-5" data-testid={`template-card-${template.key}`}><div className="flex items-center justify-between"><div className="flex items-center gap-2"><Settings2 size={16} className="text-[#0f4c81]" /><strong className="text-sm text-slate-800">{template.label}</strong></div><label className="flex items-center gap-2 text-[10px] font-bold text-slate-500"><input name="is_active" type="checkbox" defaultChecked={template.is_active} data-testid={`template-active-${template.key}`} /> Aktif</label></div><textarea name="content" required minLength={10} defaultValue={template.content} rows={5} className="form-input mt-4 resize-none" data-testid={`template-content-${template.key}`} /><p className="mt-2 text-[9px] text-slate-400">Terakhir oleh {template.updated_by} · {new Date(template.updated_at).toLocaleString("id-ID")}</p><div className="mt-4 flex gap-2"><button type="submit" className="inline-flex flex-1 items-center justify-center gap-2 rounded-xl bg-[#0f4c81] py-2.5 text-xs font-extrabold text-white" data-testid={`template-save-${template.key}`}><Save size={14} /> Simpan</button><button type="button" onClick={() => reset.mutate(template.key)} className="inline-flex items-center gap-2 rounded-xl bg-slate-100 px-4 text-xs font-bold text-slate-600" data-testid={`template-reset-${template.key}`}><RotateCcw size={14} /> Default</button></div></form>)}</div></section>;
}